import { useEffect, useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { api } from "@/lib/client";

export default function Respond(){const {challengeId}=useLocalSearchParams<{challengeId:string}>();const [body,setBody]=useState("## Assessment\n\n## Evidence\n\n## Plan\n\n## Verification\n\n## Risk and rollback\n");const [revision,setRevision]=useState(0);const [saving,setSaving]=useState(false);
 useEffect(()=>{if(challengeId)api.request<{draft?:{body:string;revision:number}}>(`/drafts/${challengeId}`).then(r=>{if(r.draft){setBody(r.draft.body);setRevision(r.draft.revision)}}).catch(()=>{})},[challengeId]);
 async function save(){setSaving(true);try{const r=await api.request<{draft:{revision:number}}>(`/drafts/${challengeId}`,{method:"PUT",body:JSON.stringify({body,attachmentIds:[],revision})});setRevision(r.draft.revision)}finally{setSaving(false)}}
 async function submit(){await save();await api.request(`/challenges/${challengeId}/submit`,{method:"POST",body:JSON.stringify({content:body,attachmentIds:[]})});Alert.alert("Response submitted","The examiner will prepare your correction.",[{text:"Done",onPress:()=>router.back()}])}
 return <KeyboardAvoidingView style={r.page} behavior={Platform.OS==="ios"?"padding":undefined}><View style={r.bar}><Pressable onPress={()=>router.back()}><Text>Close</Text></Pressable><Text style={r.saved}>{saving?"Saving...":revision?`Saved v${revision}`:"Draft"}</Text><Pressable onPress={save}><Text style={r.action}>Save</Text></Pressable></View><ScrollView contentContainerStyle={r.content} keyboardShouldPersistTaps="handled"><Text style={r.h1}>Build your response</Text><Text style={r.help}>The outline is editable. Make each claim traceable to evidence or an explicit assumption.</Text><TextInput multiline value={body} onChangeText={setBody} style={r.editor} textAlignVertical="top"/><Pressable style={r.submit} onPress={submit}><Text style={r.submitText}>Submit for assessment</Text></Pressable></ScrollView></KeyboardAvoidingView>}
const r=StyleSheet.create({page:{flex:1,backgroundColor:"#fff"},bar:{height:56,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderColor:"#dce3e4"},saved:{fontSize:12,color:"#657278"},action:{color:"#167d87",fontWeight:"700"},content:{padding:20,paddingBottom:48},h1:{fontSize:26,fontWeight:"600",color:"#172126"},help:{color:"#657278",lineHeight:21,marginTop:8,marginBottom:18},editor:{minHeight:440,borderWidth:1,borderColor:"#cfd9da",borderRadius:7,padding:16,fontSize:15,lineHeight:23,color:"#172126",fontFamily:Platform.OS==="android"?"monospace":undefined},submit:{backgroundColor:"#167d87",padding:16,borderRadius:7,alignItems:"center",marginTop:18},submitText:{color:"white",fontWeight:"700"}});
